### ISSUE TITLE
Rotations reset on unmatched frames when the source DMD frame change

### ISSUE THREAD

**Issue by Kraken74** [zesinger/libserum#44] opened 2024-02-12 12:40 UTC
Color rotations should only reset when the colorization frame matches a source DMD frame, but right now the rotations reset every time the source DMD frame changes even though the project file is unmatched.

https://imgur.com/a/YXRH13W

**Comment by Kraken74** [comment] 2024-02-12 12:48
Here is a sample crz for AFM to troubleshoot the color rotations.  The colors should rotate non-stop as only the very first frame is matched.
[https://mega.nz/folder/Qz4BnRhA#cCKY7tkmTJzXWrwxNT1yCQ](url)

**Comment by mkalkbrenner** [comment] 2024-02-18 10:24
This issue is caused by the way libserum is used in DMDext and devices (including the virtual DMD) that can't perform color rotations on their own.
If you use libserum with libdmdutil in VPX Standalone and attach a ZeDMD, the rotations won't reset. The reason is that ZeDMD is able to perform the rotations on its own until it gets a new frame. And in this setup it doesn't get a new frame.
But attached to DMDEXT, ZeDMD has the same issue as the native rotation feature is not used in this setup.

@zesinger I don't know yet, if the fix has to be done in libserum or it DMDEXT integration where the "fake" frames for rotations are created.

**Comment by mkalkbrenner** [comment] 2024-02-18 11:35
First, we need to investigate,  where the reset happens.
But I also noticed the issue since ZeDMD uses the same logic as the others in DMDEXT now instead of it's own rotations.

**Comment by zesinger** [comment] 2024-02-18 11:37
I didn't know that the color rotations were not made by the ESP32 anymore.

**Comment by mkalkbrenner** [comment] 2024-02-18 12:03
> I didn't know that the color rotations were not made by the ESP32 anymore.

Just in combination with DMDEXT. It is caused by the DMDext architecture. You can only declare compatibility to features for the entire device and not per mode. So if you implement IRotation for full compatibility, you can't use the native mode.
And libserum has the issue that you can't use two instances for the same ROM at the same time, one with the rotations as used by DMDEXT or alphaDMD and one to leverage the ZeDMD native mode.
That's why we designed libdmdutil differently.

**Comment by mkalkbrenner** [comment] 2024-02-18 12:05
So I suggest that we carefully review the issue and then take a decision how to solve it in a smart way. @jsm174 also has some thoughts about it.

**Comment by zesinger** [comment] 2024-04-20 16:30
should be fixed

**Closed** 2024-04-28 12:50 UTC
